version: '3.8'

services:
  ai-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-container
    ports:
      - "8000:80"
    volumes:
      - .:/code
    environment:
      - ENVIRONMENT=production
